import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import image from '../public/assets/home_img.png';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenue sur <a href="https://nextjs.org">Code.io</a>
        </h1>
        <p className={styles.description}>Le blog communautaire des afficionados de développement web.</p>

        <div className={styles.content}>

          <div className={styles.block} >

            <div className={styles.text}>
              <h2>Lisez les articles</h2>
              <h3>Maximiser votre culture web</h3>
              <p>Chaque auteur tente de vous apporter le plus de valeur possible par article</p>
              <Link href="/blog"><a>Visiter le blog </a></Link>
            </div>
            <div className={styles.picture}>
              <Image src={image}  ></Image>
            </div>

          </div>

          <div className={styles.block} >

            <div className={styles.text}>
              <h2>Faites un tour vers la liste des membres</h2>
              <h3>Faites-vous des amis</h3>
              <p>Ajoutez, invitez, et discutez avec les différents membres</p>
              <Link href="/liste"><a>Découvrir la liste des membres</a></Link>
            </div>
            <div className={styles.picture}>
              <Image src={image}  ></Image>
            </div>

          </div>


          <div>


          </div>

        </div>

      </main>


    </div>
  )
}
